void options( );
int admin( );
int user( );
void menu_admin( );
void menu_user( );
void clear( );
void add_record( );
void display( );
void search( );
void delete( );
void display_orders( );
void delete_orders( );
int generate_orderID();